spring:
  application:
    name: TeaMarket
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tea
    username: root
    password: 123456


server:
  port: 9099
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
