spring:
  application:
    name: TeaMarket
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tea
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9099

